### ISSUE TITLE
关于tfrecord文件编码问题

### ISSUE THREAD

**Issue by haotian233** [yeyupiaoling/VoiceprintRecognition-Tensorflow#6]
您好！我使用的是您给出链接的数据集，在使用`create_data.py`创建完成`train_dataset.tfrecord`和`test_dataset.tfrecord`后，在进行训练时，发生了错误
```
Traceback (most recent call last):
  File "train.py", line 29, in <module>
    for batch_id, data in enumerate(train_dataset):
  File "C:\Users\anaconda3\envs\py3ten2\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 622, in __next__
    return self.next()
  File "C:\Users\anaconda3\envs\py3ten2\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 666, in next
    return self._next_internal()
  File "C:\Users\anaconda3\envs\py3ten2\lib\site-packages\tensorflow_core\python\data\ops\iterator_ops.py", line 651, in _next_internal
    output_shapes=self._flat_output_shapes)
  File "C:\Users\anaconda3\envs\py3ten2\lib\site-packages\tensorflow_core\python\ops\gen_dataset_ops.py", line 2659, in iterator_get_next_sync
    "output_types", output_types, "output_shapes", output_shapes)
UnicodeDecodeError: 'utf-8' codec can't decode byte 0xd5 in position 72: invalid continuation byte
```
请问您是否遇到过这种错误呢，期待您的回复！

**Comment by haotian233** [comment]
解决了，我重新跑了一次create_data.py就可以了，非常抱歉
